[project]
name = "pi-hat-eink-2-13"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "pillow>=11.1.0",
    "plotly>=6.0.0",
    "requests>=2.32.3",
]
